version: "3.9" # optional since v1.27.0
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  dbGUI:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ben39053372@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ben39053372"
      POSTGRES_USERS: "ben:39053372|local:local"
      POSTGRES_DATABASES: "example:ben|example2:local"
    ports:
      - "16543:80"
    depends_on:
      - db
volumes:
  logvolume01: {}
